package com.code.Asgmnt1;

public interface Grammar {

	enum TokenType
	{
	PLUS, MINUS, TIMES, DIVIDE, EXPONENT, LPAREN, RPAREN, INTLIT, FLOATLIT, EOLN, DISPLAY,INPUT, 
	BLOCK, IF, THEN, ELSE, END, DO, WHILE, REPEAT, UNTIL, ASSIGN, LT, LE, GT, GE, EQ, NTEQ, IDENTIFIER, EOF, EOS
	};
	
	enum NonTerminal
	{
		PROGRAM, STATEMENT, EXPRESSION, TERM, FACTOR, EXPONENT, NEG_EXPR, NUM, RETN, 
		ASSIGNMENT, VARIABLE, DISPLAY, INPUT, BLOCK, IF, WHILE, REPEAT, BOOLEAN_EXPR, END, NONE
	}

}
